language: php

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script: ./vendor/bin/phpunit --configuration ./build/travis-ci.xml

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f89255465d5a7b644fee
    on_success: always
    on_failure: always
    on_start: false

